site_name: SMTR Data Engineering Challenge
site_url: https://limazix.github.io/smtr-data-engineering-challenge
site_author: Bruno Lima Cardoso <blimacardoso@gmail.com>

# Repository
repo_name: smtr-data-engineering-challenge
repo_url: https://github.com/limazix/smtr-data-engineering-challenge
edit_uri: edit/main/docs
docs_dir: docs

plugins:
    - awesome-pages
    - search

theme:
  name: readthedocs

nav:
- Home: README.md
- API: overview.md
- Coverage: coverage.md

plugins:
- coverage:
    page_name: coverage  # default
    html_report_dir: htmlcov  # default
